import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { del, get, patch, post } from './lib/api';
import { initTelegram } from './lib/telegram';
import './styles.css';

type Role='ADMIN'|'USER';
type Section='home'|'calendar'|'lists'|'notes'|'ideas'|'finance'|'family';
type ModalKind='list'|'item'|'member'|'transaction'|'goal'|'card'|'cashback'|'contribution'|'price'|'receipt'|null;

type User={id:string;telegram_user_id:number;username?:string|null;first_name:string;last_name?:string|null;avatar_url?:string|null;timezone:string;locale?:string|null};
type Member={id:string;role:Role;status:string;joined_at?:string|null;user:User};
type Family={id:string;name:string;status:string;my_role:Role;members:Member[]};
type ListItem={id:string;list_id:string;title:string;is_completed:boolean;created_by:string;completed_by?:string|null;completed_at?:string|null;position:number};
type FamilyList={id:string;name:string;type:string;items:ListItem[]};
type Invitation={id:string;family_id:string;telegram_user_id?:number|null;username?:string|null;first_name?:string|null;status:string;expires_at?:string|null;family?:Family;inviter?:User};
type FinanceTransaction={id:string;type:'INCOME'|'EXPENSE';amount:string|number;category:string;budget_type:string;description?:string|null;occurred_on:string};
type FinanceData={data:FinanceTransaction[];summary:{income:number;expense:number;balance:number}};
type Goal={id:string;name:string;type:string;target_amount:number;current_price?:number|null;target_date?:string|null;priority:string;status:string;description?:string|null;url?:string|null;contributions?:Contribution[];price_history?:PricePoint[]};
type Contribution={id:string;goal_id:string;amount:number;contribution_date:string;comment?:string|null};
type PricePoint={id:string;goal_id:string;price:number;recorded_at:string;url?:string|null;comment?:string|null};
type Card={id:string;name:string;bank_name?:string|null;last4?:string|null;payment_system?:string|null;default_cashback_rate:number;status:string;notes?:string|null};
type Cashback={id:string;card_id?:string|null;merchant_name?:string|null;category?:string|null;cashback_rate:number;cap_amount?:number|null;valid_from?:string|null;valid_to?:string|null;notes?:string|null};
type Credit={id:string;name:string;principal:string|number;annual_rate:string|number;standard_payment:string|number;term_months:number;start_date:string;first_payment_date:string;recalculation_mode:'TERM'|'PAYMENT';payment_schedule:any[];prepayments?:any[]};
type EventItem={id:string;title:string;description?:string|null;start_at:string;end_at:string;timezone:string;location?:string|null;status:string;recurrence_rule?:string|null;responsible_member_id?:string|null;responsibleMember?:Member|null};
type Reminder={id:string;title:string;description?:string|null;scheduled_at:string;timezone:string;status:string;recurrence_rule?:string|null;responsible_member_id?:string|null;responsibleMember?:Member|null};
type Receipt={id:string;file_name?:string|null;mime_type?:string|null;ocr_status:string;ocr_text?:string|null;ai_result?:any;created_at:string;expense_id?:string|null};

const MOSCOW='Europe/Moscow';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:MOSCOW,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const rub=(v:number)=>`${v.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})} ₽`;
const n=(v:unknown)=>{const x=typeof v==='number'?v:Number(String(v??'').replace(',','.'));return Number.isFinite(x)?x:0};

// Lightweight routing for Telegram deep links & browser history — mobile-friendly
const pathToSection = (path: string): Section | null => {
  const p = path.replace(/\/+$/,'') || '/';
  if (p === '/' || p === '/home') return 'home';
  if (p.startsWith('/calendar')) return 'calendar';
  if (p.startsWith('/lists')) return 'lists';
  if (p.startsWith('/notes')) return 'notes';
  if (p.startsWith('/ideas')) return 'ideas';
  if (p.startsWith('/finance')) return 'finance';
  if (p.startsWith('/family') || p.startsWith('/settings')) return 'family';
  return null;
};
const sectionToPath = (s: Section): string => ({home:'/',calendar:'/calendar',lists:'/lists',notes:'/notes',ideas:'/ideas',finance:'/finance',family:'/family'}[s] || '/');

export default function App(){
 const [section,setSection]=useState<Section>('home');
 const [me,setMe]=useState<User|null>(null); const [family,setFamily]=useState<Family|null>(null); const [events,setEvents]=useState<EventItem[]>([]); const [reminders,setReminders]=useState<Reminder[]>([]); const [lists,setLists]=useState<FamilyList[]>([]); const [notes,setNotes]=useState<any[]>([]); const [ideas,setIdeas]=useState<any[]>([]); const [finance,setFinance]=useState<FinanceData|null>(null); const [credits,setCredits]=useState<Credit[]>([]); const [invitations,setInvitations]=useState<Invitation[]>([]);
 const [busy,setBusy]=useState(true); const [error,setError]=useState<string|null>(null); const [modal,setModal]=useState<ModalKind>(null); const [activeList,setActiveList]=useState<FamilyList|null>(null); const [editingItem,setEditingItem]=useState<ListItem|null>(null); const [editingList,setEditingList]=useState<FamilyList|null>(null); const [selectedGoal,setSelectedGoal]=useState<Goal|null>(null);
 const [goals,setGoals]=useState<Goal[]>([]); const [cards,setCards]=useState<Card[]>([]); const [cashbacks,setCashbacks]=useState<Cashback[]>([]); const [receipts,setReceipts]=useState<Receipt[]>([]); const [analytics,setAnalytics]=useState<any>(null); const [budget,setBudget]=useState<any>(null);
  const loadCore=async()=>{setError(null);try{const meR=await get<{data:User}>('/me');setMe(meR.data);const invR=await get<{data:Invitation[]}>('/family/invitations').catch(()=>({data:[]}));setInvitations(invR.data??[]);const fam=await get<{data:Family}>('/family').catch(()=>null);if(!fam?.data){setFamily(null);return;}setFamily(fam.data);const [ev,rem,l,n,i]=await Promise.all([get<{data:EventItem[]}>('/events'),get<{data:Reminder[]}>('/reminders'),get<{data:FamilyList[]}>('/lists'),get<{data:any[]}>('/notes'),get<{data:any[]}>('/ideas')]);setEvents(ev.data??[]);setReminders(rem.data??[]);setLists(l.data);setNotes(n.data);setIdeas(i.data);if(fam.data.my_role==='ADMIN'){const [fin,cr,gg,cc,cb,rr]=await Promise.all([get<FinanceData>('/finances'),get<{data:Credit[]}>('/credits'),get<{data:Goal[]}>('/finance/goals'),get<{data:Card[]}>('/finance/cards'),get<{data:Cashback[]}>('/finance/cashback'),get<{data:Receipt[]}>('/finance/receipts')]);setFinance(fin);setCredits(cr.data);setGoals(gg.data);setCards(cc.data);setCashbacks(cb.data);setReceipts(rr.data);try{const an=await get<any>('/finance/analytics');setAnalytics(an.data)}catch{}try{const b=await get<any>(`/finance/budgets/${new Date().getFullYear()}/${new Date().getMonth()+1}`);setBudget(b.data)}catch{}}}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить Family Hub.')}finally{setBusy(false)}};
  // Deep-link & Telegram start_param routing
  useEffect(()=>{
    initTelegram();
    const initial = pathToSection(window.location.pathname) || 'home';
    const startParam = new URLSearchParams(window.location.search).get('tgWebAppStartParam') || (window as any).Telegram?.WebApp?.initDataUnsafe?.start_param;
    if (startParam) {
      const mapped = pathToSection('/' + String(startParam).replace(/^\/+/, ''));
      if (mapped) { setSection(mapped); window.history.replaceState({}, '', sectionToPath(mapped)); }
      else setSection(initial);
    } else {
      setSection(initial);
    }
    const onPop = () => { const s = pathToSection(window.location.pathname); if (s) setSection(s); };
    window.addEventListener('popstate', onPop);
    void loadCore();
    return () => window.removeEventListener('popstate', onPop);
  },[]);
  const navigate = (s: Section) => { setSection(s); try { window.history.pushState({}, '', sectionToPath(s)); } catch {} };
  const accept=async(inv:Invitation)=>{try{await post(`/family/invitations/${inv.id}/accept`,{});await loadCore();navigate('home')}catch(e){setError(e instanceof Error?e.message:'Не удалось принять приглашение')}};
  const createFamily=async(name:string)=>{try{await post('/families',{name});await loadCore();navigate('home')}catch(e){setError(e instanceof Error?e.message:'Не удалось создать семью')}};
 const saveList=async(name:string)=>{try{if(editingList){await patch(`/lists/${editingList.id}`,{name});}else{await post('/lists',{name,type:'CUSTOM'});}setEditingList(null);setModal(null);await loadCore()}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить список')}};
 const saveItem=async(title:string)=>{if(!activeList)return;try{if(editingItem){await patch(`/lists/${activeList.id}/items/${editingItem.id}`,{title});}else{await post(`/lists/${activeList.id}/items`,{title});}setEditingItem(null);setModal(null);await loadCore()}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить пункт')}};
 const removeItem=async(item:ListItem)=>{if(!activeList)return;try{await del(`/lists/${activeList.id}/items/${item.id}`);await loadCore()}catch(e){setError(e instanceof Error?e.message:'Не удалось удалить пункт')}};
 const toggleItem=async(item:ListItem)=>{if(!activeList)return;try{await patch(`/lists/${activeList.id}/items/${item.id}`,{is_completed:!item.is_completed});await loadCore()}catch(e){setError(e instanceof Error?e.message:'Не удалось изменить пункт')}};
 if(busy)return <div className="loading">Загружаем Family Hub…</div>;
 return <div className="app-shell"><header className="topbar"><div><div className="eyebrow">Семья</div><h1>{family?.name??'Family Hub'}</h1></div><div className="user-badge">{me?.first_name?.slice(0,1)??'?'}</div></header>{error&&<div className="error-banner">{error}<button onClick={()=>setError(null)}>×</button></div>}
    {!family?<main className="page">{invitations.length>0?<InvitationView invitations={invitations} onAccept={accept}/>:<NoFamilyView onCreate={createFamily}/>}</main>:<main className="page">{section==='home'&&<HomeView family={family} lists={lists} finance={finance} goals={goals} onSection={navigate} onAccept={accept} invitations={invitations}/>} {section==='calendar'&&<CalendarView events={events} reminders={reminders} members={family?.members??[]} onReload={loadCore}/>} {section==='lists'&&<ListsView lists={lists} activeList={activeList??lists[0]??null} setActiveList={setActiveList} onNewList={()=>{setEditingList(null);setModal('list')}} onEditList={(l)=>{setEditingList(l);setModal('list')}} onDeleteList={async(l)=>{if(!confirm('Удалить список?'))return;await del(`/lists/${l.id}`);await loadCore()}} onAdd={()=>{setEditingItem(null);setModal('item')}} onEdit={(it)=>{setEditingItem(it);setModal('item')}} onDelete={removeItem} onToggle={toggleItem}/>} {section==='notes'&&<SimpleCrud title="Мои заметки" items={notes} kind="note" onSave={async(data)=>{await post('/notes',data);await loadCore()}} onDelete={async(id)=>{await del(`/notes/${id}`);await loadCore()}}/>} {section==='ideas'&&<SimpleCrud title="Семейные идеи" items={ideas} kind="idea" onSave={async(data)=>{await post('/ideas',data);await loadCore()}} onDelete={async(id)=>{await del(`/ideas/${id}`);await loadCore()}}/>} {section==='finance'&&<FinanceView finance={finance} goals={goals} cards={cards} cashbacks={cashbacks} receipts={receipts} analytics={analytics} budget={budget} credits={credits} onReload={loadCore}/>} {section==='family'&&<FamilyView family={family} invitations={invitations} onInvite={async(data)=>{await post('/family/invitations',data);await loadCore()}} onAccept={accept}/>}</main>}
    <nav className="bottom-nav"><Nav a={section==='home'} l="Главная" c={()=>navigate('home')} i="⌂"/><Nav a={section==='calendar'} l="Календарь" c={()=>navigate('calendar')} i="□"/><Nav a={section==='lists'} l="Списки" c={()=>navigate('lists')} i="☷"/><Nav a={section==='finance'} l="Финансы" c={()=>navigate('finance')} i="₽"/><Nav a={section==='family'} l="Семья" c={()=>navigate('family')} i="👨‍👩‍👧"/><Nav a={section==='notes'} l="Ещё" c={()=>navigate('notes')} i="•••"/></nav>
   {modal==='list'&&<FormModal title={editingList?'Редактировать список':'Новый список'} fields={[{name:'name',label:'Название',defaultValue:editingList?.name??''}]} onClose={()=>{setModal(null);setEditingList(null)}} onSave={(d)=>saveList(d.name)}/>} {modal==='item'&&<FormModal title={editingItem?'Редактировать пункт':'Добавить пункт'} fields={[{name:'title',label:'Название пункта',defaultValue:editingItem?.title??''}]} onClose={()=>{setModal(null);setEditingItem(null)}} onSave={(d)=>saveItem(d.title)}/>} </div>
}


function NoFamilyView(p:{onCreate:(name:string)=>Promise<void>}){const [name,setName]=useState('');return <div className="stack"><SectionTitle title="Создадим семью" subtitle="После создания можно сразу приглашать участников"/><Card title="Новая семья"><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(!name.trim())return;await p.onCreate(name.trim())}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Например, Наша семья"/><button className="button primary">Создать семью</button></form></Card></div>}
function Nav(p:{a:boolean;l:string;c:()=>void;i:string}){return <button className={p.a?'nav-item active':'nav-item'} onClick={p.c}><span>{p.i}</span><small>{p.l}</small></button>}
function InvitationView(p:{invitations:Invitation[];onAccept:(i:Invitation)=>void}){return <div className="stack"><SectionTitle title="Приглашение в семью" subtitle="Сначала примите приглашение"/>{p.invitations.map(i=><Card key={i.id} title={i.family?.name??'Семья'}><p>Вас приглашает <strong>{i.inviter?.first_name??i.first_name??'член семьи'}</strong>.</p><button className="button primary full" onClick={()=>p.onAccept(i)}>Принять приглашение</button></Card>)}</div>}
function HomeView(p:{family:Family|null;lists:FamilyList[];finance:FinanceData|null;goals:Goal[];onSection:(s:Section)=>void;onAccept:(i:Invitation)=>void;invitations:Invitation[]}){const open=p.lists.flatMap(x=>x.items).filter(x=>!x.is_completed).slice(0,5);return <div className="stack"><SectionTitle title="Сегодня" subtitle={new Intl.DateTimeFormat('ru-RU',{timeZone:MOSCOW,day:'numeric',month:'long'}).format(new Date())}/>{p.invitations.length>0&&<InvitationView invitations={p.invitations} onAccept={p.onAccept}/>}<div className="grid-2"><Card title="Список">{p.lists[0]?<><strong>{p.lists[0].name}</strong>{open.map(i=><div className="list-row" key={i.id}><span className="checkbox"/>{i.title}</div>)}<button className="button primary full" onClick={()=>p.onSection('lists')}>Открыть список</button></>:<><p className="muted">Списков пока нет.</p><button className="button primary full" onClick={()=>p.onSection('lists')}>Создать список</button></>}</Card><Card title="Финансы">{p.finance?<><Metric title="Доходы" value={p.finance.summary.income}/><Metric title="Расходы" value={p.finance.summary.expense}/><Metric title="Баланс" value={p.finance.summary.balance}/></>:<p className="muted">Финансы доступны администратору.</p>}</Card></div><Card title="Цели">{p.goals.length?p.goals.slice(0,3).map(g=><div className="goal-row" key={g.id}><div><strong>{g.name}</strong><small>{rub(pctAmount(g))} из {rub(g.target_amount)}</small></div><div className="progress"><span style={{width:`${Math.min(100,pct(g))}%`}}/></div></div>):<p className="muted">Целей пока нет.</p>}</Card></div>}
const pct=(g:Goal)=>{const c=(g.contributions??[]).reduce((s,x)=>s+n(x.amount),0);return g.target_amount>0?c/g.target_amount*100:0}; const pctAmount=(g:Goal)=>Math.round((g.contributions??[]).reduce((s,x)=>s+n(x.amount),0)*100)/100;
function CalendarView(p:{events:EventItem[];reminders:Reminder[];members:Member[];onReload:()=>Promise<void>}){
 const [eventForm,setEventForm]=useState({title:'',date:today(),start:'10:00',end:'11:00',location:'',description:'',recurrence_rule:'',responsible_member_id:p.members[0]?.id??''});
 const [remForm,setRemForm]=useState({title:'',date:today(),time:'18:00',description:'',recurrence_rule:'',responsible_member_id:p.members[0]?.id??''});
 const [open,setOpen]=useState<'event'|'reminder'|null>(null); const [saving,setSaving]=useState(false);
 const saveEvent=async(e:React.FormEvent)=>{e.preventDefault();if(!eventForm.title.trim())return;setSaving(true);try{await post('/events',{title:eventForm.title.trim(),description:eventForm.description||null,start_at:`${eventForm.date}T${eventForm.start}:00`,end_at:`${eventForm.date}T${eventForm.end}:00`,timezone:MOSCOW,location:eventForm.location||null,responsible_member_id:eventForm.responsible_member_id||p.members[0]?.id,participant_member_ids:eventForm.responsible_member_id?[eventForm.responsible_member_id]:[] ,recurrence_rule:eventForm.recurrence_rule||null});setEventForm({...eventForm,title:'',description:'',location:'',recurrence_rule:''});setOpen(null);await p.onReload()}catch(err){alert(err instanceof Error?err.message:'Не удалось сохранить событие')}finally{setSaving(false)}};
 const saveReminder=async(e:React.FormEvent)=>{e.preventDefault();if(!remForm.title.trim())return;setSaving(true);try{await post('/reminders',{title:remForm.title.trim(),description:remForm.description||null,scheduled_at:`${remForm.date}T${remForm.time}:00`,timezone:MOSCOW,responsible_member_id:remForm.responsible_member_id||p.members[0]?.id,recurrence_rule:remForm.recurrence_rule||null});setRemForm({...remForm,title:'',description:'',recurrence_rule:''});setOpen(null);await p.onReload()}catch(err){alert(err instanceof Error?err.message:'Не удалось сохранить напоминание')}finally{setSaving(false)}};
 const editEvent=async(item:EventItem)=>{const title=prompt('Название события',item.title);if(!title?.trim())return;try{await patch(`/events/${item.id}`,{title:title.trim()});await p.onReload()}catch(err){alert(err instanceof Error?err.message:'Не удалось изменить событие')}};
 const deleteEvent=async(item:EventItem)=>{if(!confirm(`Удалить событие «${item.title}»?`))return;try{await del(`/events/${item.id}`);await p.onReload()}catch(err){alert(err instanceof Error?err.message:'Не удалось удалить событие')}};
 const editReminder=async(item:Reminder)=>{const title=prompt('Название напоминания',item.title);if(!title?.trim())return;try{await patch(`/reminders/${item.id}`,{title:title.trim()});await p.onReload()}catch(err){alert(err instanceof Error?err.message:'Не удалось изменить напоминание')}};
 const deleteReminder=async(item:Reminder)=>{if(!confirm(`Удалить напоминание «${item.title}»?`))return;try{await del(`/reminders/${item.id}`);await p.onReload()}catch(err){alert(err instanceof Error?err.message:'Не удалось удалить напоминание')}};
 const sortedEvents=[...p.events].sort((a,b)=>a.start_at.localeCompare(b.start_at)); const sortedReminders=[...p.reminders].sort((a,b)=>a.scheduled_at.localeCompare(b.scheduled_at));
 return <div className="stack"><SectionTitle title="Календарь" subtitle={`Москва · ${new Intl.DateTimeFormat('ru-RU',{timeZone:MOSCOW,day:'numeric',month:'long',year:'numeric'}).format(new Date())}`} action={<div className="calendar-actions"><button className="button primary" onClick={()=>setOpen('event')}>＋ Событие</button><button className="button secondary" onClick={()=>setOpen('reminder')}>＋ Напоминание</button></div>}/>
 {open==='event'&&<Card title="Новое событие"><form className="form-grid" onSubmit={saveEvent}><input required value={eventForm.title} onChange={e=>setEventForm({...eventForm,title:e.target.value})} placeholder="Название"/><input type="date" value={eventForm.date} onChange={e=>setEventForm({...eventForm,date:e.target.value})}/><input type="time" value={eventForm.start} onChange={e=>setEventForm({...eventForm,start:e.target.value})}/><input type="time" value={eventForm.end} onChange={e=>setEventForm({...eventForm,end:e.target.value})}/><input value={eventForm.location} onChange={e=>setEventForm({...eventForm,location:e.target.value})} placeholder="Место"/><select value={eventForm.responsible_member_id} onChange={e=>setEventForm({...eventForm,responsible_member_id:e.target.value})}>{p.members.map(m=><option key={m.id} value={m.id}>{m.user.first_name}</option>)}</select><input value={eventForm.recurrence_rule} onChange={e=>setEventForm({...eventForm,recurrence_rule:e.target.value})} placeholder="Повторение (необязательно)"/><textarea className="wide" value={eventForm.description} onChange={e=>setEventForm({...eventForm,description:e.target.value})} placeholder="Описание"/><div className="modal-actions wide"><button type="button" className="button secondary" onClick={()=>setOpen(null)}>Отмена</button><button className="button primary" disabled={saving}>Сохранить</button></div></form></Card>}
 {open==='reminder'&&<Card title="Новое напоминание"><form className="form-grid" onSubmit={saveReminder}><input required value={remForm.title} onChange={e=>setRemForm({...remForm,title:e.target.value})} placeholder="Название"/><input type="date" value={remForm.date} onChange={e=>setRemForm({...remForm,date:e.target.value})}/><input type="time" value={remForm.time} onChange={e=>setRemForm({...remForm,time:e.target.value})}/><select value={remForm.responsible_member_id} onChange={e=>setRemForm({...remForm,responsible_member_id:e.target.value})}>{p.members.map(m=><option key={m.id} value={m.id}>{m.user.first_name}</option>)}</select><input value={remForm.recurrence_rule} onChange={e=>setRemForm({...remForm,recurrence_rule:e.target.value})} placeholder="Повторение (необязательно)"/><textarea className="wide" value={remForm.description} onChange={e=>setRemForm({...remForm,description:e.target.value})} placeholder="Описание"/><div className="modal-actions wide"><button type="button" className="button secondary" onClick={()=>setOpen(null)}>Отмена</button><button className="button primary" disabled={saving}>Сохранить</button></div></form></Card>}
 <Card title="События">{sortedEvents.length?sortedEvents.map(x=><div className="calendar-row" key={x.id}><div><strong>{x.title}</strong><small>{x.start_at.slice(0,10)} · {x.start_at.slice(11,16)}–{x.end_at.slice(11,16)} · Москва</small>{x.location&&<small>{x.location}</small>}{x.recurrence_rule&&<small>Повторяется: {x.recurrence_rule}</small>}</div><div className="row-actions"><button onClick={()=>editEvent(x)}>✎</button><button className="danger" onClick={()=>deleteEvent(x)}>×</button></div></div>):<p className="muted">Событий пока нет.</p>}</Card>
 <Card title="Напоминания">{sortedReminders.length?sortedReminders.map(x=><div className="calendar-row" key={x.id}><div><strong>{x.title}</strong><small>{x.scheduled_at.slice(0,10)} · {x.scheduled_at.slice(11,16)} · Москва</small>{x.recurrence_rule&&<small>Повторяется: {x.recurrence_rule}</small>}</div><div className="row-actions"><button onClick={()=>editReminder(x)}>✎</button><button className="danger" onClick={()=>deleteReminder(x)}>×</button></div></div>):<p className="muted">Напоминаний пока нет.</p>}</Card></div>}

function ListsView(p:{lists:FamilyList[];activeList:FamilyList|null;setActiveList:(l:FamilyList)=>void;onNewList:()=>void;onEditList:(l:FamilyList)=>void;onDeleteList:(l:FamilyList)=>void;onAdd:()=>void;onEdit:(i:ListItem)=>void;onDelete:(i:ListItem)=>void;onToggle:(i:ListItem)=>void}){const l=p.activeList;return <div className="stack"><SectionTitle title="Списки" subtitle="Общие семейные списки" action={<button className="icon-button" onClick={p.onNewList}>＋</button>}/><div className="list-switcher">{p.lists.map(x=><button key={x.id} className={l?.id===x.id?'chip active':'chip'} onClick={()=>p.setActiveList(x)}>{x.name}</button>)}</div>{l?<Card title={l.name} actions={<><button className="tiny" onClick={()=>p.onEditList(l)}>Изменить</button><button className="tiny danger" onClick={()=>p.onDeleteList(l)}>Удалить</button></>}><div className="stack compact">{l.items.map(i=><div className="list-item-card" key={i.id}><button className={i.is_completed?'checkbox checked':'checkbox'} onClick={()=>p.onToggle(i)}>{i.is_completed?'✓':''}</button><span className={i.is_completed?'done':''}>{i.title}</span><div className="row-actions"><button onClick={()=>p.onEdit(i)}>✎</button><button className="danger" onClick={()=>p.onDelete(i)}>×</button></div></div>)}{!l.items.length&&<p className="muted">В списке пока нет пунктов.</p>}</div><button className="button primary full" onClick={p.onAdd}>＋ Добавить пункт списка</button></Card>:<Card title="Новый список"><p className="muted">Создайте первый список семьи.</p><button className="button primary full" onClick={p.onNewList}>Создать список</button></Card>}</div>}
function SimpleCrud(p:{title:string;items:any[];kind:'note'|'idea';onSave:(d:any)=>Promise<void>;onDelete:(id:string)=>Promise<void>}){const [title,setTitle]=useState('');const [body,setBody]=useState('');return <div className="stack"><SectionTitle title={p.title}/><Card title={p.kind==='note'?'Новая заметка':'Новая идея'}><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(!title.trim())return;await p.onSave(p.kind==='note'?{title,body}:{title,description:body});setTitle('');setBody('')}}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Название"/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Описание"/><button className="button primary">Сохранить</button></form></Card>{p.items.map(x=><Card key={x.id} title={x.title}><p>{x.body??x.description}</p><button className="button secondary" onClick={()=>p.onDelete(x.id)}>Удалить</button></Card>)}</div>}

function FamilyView(p:{family:Family|null;invitations:Invitation[];onInvite:(d:any)=>Promise<void>;onAccept:(i:Invitation)=>void}){const [mode,setMode]=useState<'username'|'id'>('username');const [value,setValue]=useState('');const [first,setFirst]=useState('');const [msg,setMsg]=useState<string|null>(null);return <div className="stack"><SectionTitle title="Семья" subtitle="Участники и приглашения"/><Card title="Участники">{p.family?.members.map(m=><div className="member-row" key={m.id}><div><strong>{m.user.first_name} {m.user.last_name??''}</strong><small>{m.user.username?`@${m.user.username}`:`Telegram ID ${m.user.telegram_user_id}`}</small></div><span className="role-badge">{m.role==='ADMIN'?'Админ':'Участник'}</span></div>)}</Card><Card title="Пригласить в семью"><div className="segmented"><button className={mode==='username'?'active':''} onClick={()=>setMode('username')}>По логину</button><button className={mode==='id'?'active':''} onClick={()=>setMode('id')}>По ID</button></div><div className="form-stack"><input value={value} onChange={e=>setValue(e.target.value)} placeholder={mode==='username'?'@username':'Telegram ID'}/>{mode==='id'&&<input value={first} onChange={e=>setFirst(e.target.value)} placeholder="Имя (необязательно)"/>}<button className="button primary" onClick={async()=>{try{await p.onInvite(mode==='username'?{username:value.replace(/^@/,'')||null,telegram_user_id:null,first_name:first||null}:{telegram_user_id:Number(value),username:null,first_name:first||null});setValue('');setFirst('');setMsg('Приглашение отправлено.')}catch(e){setMsg(e instanceof Error?e.message:'Ошибка')}}}>Отправить приглашение</button>{msg&&<p className="muted">{msg}</p>}</div></Card>{p.invitations.length>0&&<Card title="Входящие приглашения">{p.invitations.map(i=><div className="inv-row" key={i.id}><span>{i.family?.name??'Семья'}</span><button className="button secondary" onClick={()=>p.onAccept(i)}>Принять</button></div>)}</Card>}</div>}

function FinanceView(p:{finance:FinanceData|null;goals:Goal[];cards:Card[];cashbacks:Cashback[];receipts:Receipt[];analytics:any;budget:any;credits:Credit[];onReload:()=>Promise<void>}){const [tab,setTab]=useState('overview');const [type,setType]=useState<'INCOME'|'EXPENSE'>('EXPENSE');const [amount,setAmount]=useState('');const [category,setCategory]=useState('');const [date,setDate]=useState(today());const [desc,setDesc]=useState(''); const [modal,setModal]=useState<string|null>(null);const [receiptData,setReceiptData]=useState<any>(null);
 const saveTx=async(e:FormEvent)=>{e.preventDefault();await post('/finances',{type,amount:Number(amount),category,budget_type:type==='EXPENSE'?'FLEXIBLE':'FIXED',description:desc,occurred_on:date});setAmount('');setDesc('');await p.onReload()};
 const expenseBy=p.analytics?.expense_chart??[];
 return <div className="stack"><SectionTitle title="Финансы" subtitle="Все данные сохраняются в базе семьи"/><div className="finance-tabs">{[['overview','Обзор'],['budget','Бюджет'],['goals','Цели'],['large','Крупные покупки'],['cards','Карты / cashback'],['receipts','Чеки'],['credits','Кредиты']].map(([k,l])=><button key={k} className={tab===k?'finance-tab active':'finance-tab'} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==='overview'&&<><div className="grid-3"><Metric title="Доходы" value={p.finance?.summary.income??0}/><Metric title="Расходы" value={p.finance?.summary.expense??0}/><Metric title="Баланс" value={p.finance?.summary.balance??0}/></div><Card title="Добавить операцию"><form className="form-grid" onSubmit={saveTx}><select value={type} onChange={e=>setType(e.target.value as any)}><option value="EXPENSE">Расход</option><option value="INCOME">Доход</option></select><input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Сумма" required/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Категория" required/><input type="date" value={date} onChange={e=>setDate(e.target.value)} required/><input className="wide" value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Комментарий"/><button className="button primary wide">Сохранить</button></form></Card><Card title="AI review"><button className="button primary full" onClick={async()=>{const r=await post<any>('/finance/ai-review',{});alert(r.data?.text??'AI review готов') }}>Получить финансовый разбор</button><p className="muted">Без персональных данных: анализ агрегированных сумм, бюджета и расходов.</p></Card><Card title="Аналитика расходов">{expenseBy.length?expenseBy.map((x:any)=><div className="bar-row" key={x.name}><div><strong>{x.name}</strong><span>{rub(n(x.amount))} · {x.percent}%</span></div><div className="progress"><span style={{width:`${x.percent}%`}}/></div></div>):<p className="muted">Нет подтверждённых расходов.</p>}</Card></>}
 {tab==='budget'&&<BudgetPanel budget={p.budget} onReload={p.onReload}/>} {tab==='goals'&&<GoalsPanel goals={p.goals} onReload={p.onReload}/>} {tab==='large'&&<LargePanel goals={p.goals} onReload={p.onReload}/>} {tab==='cards'&&<CardsPanel cards={p.cards} cashbacks={p.cashbacks} onReload={p.onReload}/>} {tab==='receipts'&&<ReceiptsPanel receipts={p.receipts} onReload={p.onReload}/>} {tab==='credits'&&<CreditsPanel credits={p.credits}/>} </div>}

function BudgetPanel(p:{budget:any;onReload:()=>Promise<void>}){const [total,setTotal]=useState(String(p.budget?.budget?.total_limit??''));return <Card title="Месячный бюджет"><div className="summary-line"><span>Лимит</span><strong>{rub(n(p.budget?.budget?.total_limit))}</strong></div><div className="form-stack"><input type="number" step="0.01" value={total} onChange={e=>setTotal(e.target.value)} placeholder="Лимит месяца"/><button className="button primary" onClick={async()=>{await fetchBudgetSave(Number(total));await p.onReload()}}>Сохранить бюджет</button></div>{p.budget?.budget?.categories?.map((c:any)=><div className="budget-row" key={c.category_id}><div><strong>{c.name}</strong><span>{rub(n(c.spent_amount))} / {rub(n(c.limit_amount))}</span></div><div className="progress"><span style={{width:`${Math.min(100,c.progress_percent)}%`}}/></div></div>)}</Card>}
async function fetchBudgetSave(total:number){await post('/finance/budgets/save',{year:new Date().getFullYear(),month:new Date().getMonth()+1,total_limit:total,categories:[]})}
function GoalsPanel(p:{goals:Goal[];onReload:()=>Promise<void>}){const [name,setName]=useState('');const [target,setTarget]=useState('');return <div className="stack"><Card title="Новая финансовая цель"><form className="form-grid" onSubmit={async e=>{e.preventDefault();await post('/finance/goals',{name,type:'SAVING',target_amount:Number(target),priority:'MEDIUM',status:'PLANNED'});setName('');setTarget('');await p.onReload()}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Название цели" required/><input type="number" step="0.01" value={target} onChange={e=>setTarget(e.target.value)} placeholder="Цель, ₽" required/><button className="button primary wide">Создать</button></form></Card>{p.goals.map(g=><Card key={g.id} title={g.name}><div className="summary-line"><span>{rub(g.contributions?.reduce((s,x)=>s+n(x.amount),0)??0)} / {rub(g.target_amount)}</span><strong>{Math.round(pct(g))}%</strong></div><div className="progress"><span style={{width:`${Math.min(100,pct(g))}%`}}/></div><div className="goal-actions"><button className="button secondary" onClick={async()=>{const v=prompt('Сумма взноса');if(v){await post(`/finance/goals/${g.id}/contributions`,{amount:Number(v),contribution_date:today()});await p.onReload()}}}>＋ Внести</button><button className="button secondary" onClick={async()=>{const v=prompt('Новая цена');if(v){await post(`/finance/goals/${g.id}/prices`,{price:Number(v),recorded_at:new Date().toISOString()});await p.onReload()}}}>Цена</button></div>{g.price_history?.slice?.(0,5)?.map(pr=><small key={pr.id} className="history-row">{rub(n(pr.price))} · {new Date(pr.recorded_at).toLocaleDateString('ru-RU')}</small>)}</Card>)}</div>}
function LargePanel(p:{goals:Goal[];onReload:()=>Promise<void>}){const [name,setName]=useState('');const [target,setTarget]=useState('');return <div className="stack"><Card title="Новая крупная покупка"><form className="form-grid" onSubmit={async e=>{e.preventDefault();await post('/finance/goals',{name,type:'LARGE_PURCHASE',target_amount:Number(target),priority:'HIGH',status:'PLANNED'});setName('');setTarget('');await p.onReload()}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Что купить" required/><input value={target} onChange={e=>setTarget(e.target.value)} type="number" step="0.01" placeholder="Стоимость, ₽" required/><button className="button primary wide">Добавить</button></form></Card>{p.goals.filter(g=>g.type==='LARGE_PURCHASE').map(g=><Card key={g.id} title={g.name}><div className="summary-line"><span>Накоплено</span><strong>{rub(pctAmount(g))} / {rub(g.target_amount)}</strong></div><div className="progress"><span style={{width:`${Math.min(100,pct(g))}%`}}/></div><button className="button secondary full" onClick={async()=>{const v=prompt('Сумма накопления');if(v){await post(`/finance/goals/${g.id}/contributions`,{amount:Number(v),contribution_date:today()});await p.onReload()}}}>＋ Внести сумму</button></Card>)}</div>}
function CardsPanel(p:{cards:Card[];cashbacks:Cashback[];onReload:()=>Promise<void>}){const [name,setName]=useState('');const [bank,setBank]=useState('');const [rate,setRate]=useState('');const [merchant,setMerchant]=useState('');return <div className="stack"><Card title="Новая карта"><form className="form-grid" onSubmit={async e=>{e.preventDefault();await post('/finance/cards',{name,bank_name:bank,default_cashback_rate:Number(rate||0)});setName('');setBank('');setRate('');await p.onReload()}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Название карты" required/><input value={bank} onChange={e=>setBank(e.target.value)} placeholder="Банк"/><input value={rate} onChange={e=>setRate(e.target.value)} type="number" step="0.01" placeholder="Cashback %"/><button className="button primary wide">Добавить карту</button></form></Card><Card title="Карты">{p.cards.map(c=><div className="member-row" key={c.id}><div><strong>{c.name}</strong><small>{c.bank_name??''} · базовый cashback {c.default_cashback_rate}%</small></div><button className="danger" onClick={async()=>{await del(`/finance/cards/${c.id}`);await p.onReload()}}>×</button></div>)}</Card><Card title="Cashback предложения"><form className="form-stack" onSubmit={async e=>{e.preventDefault();await post('/finance/cashback',{merchant_name:merchant,cashback_rate:Number(rate||0)});setMerchant('');await p.onReload()}}><input value={merchant} onChange={e=>setMerchant(e.target.value)} placeholder="Магазин"/><input value={rate} onChange={e=>setRate(e.target.value)} type="number" step="0.01" placeholder="Cashback %"/><button className="button primary">Добавить предложение</button></form>{p.cashbacks.map(c=><div className="summary-line" key={c.id}><span>{c.merchant_name??c.category??'Без названия'}</span><strong>{c.cashback_rate}%</strong></div>)}</Card></div>}
function ReceiptsPanel(p:{receipts:Receipt[];onReload:()=>Promise<void>}){const [file,setFile]=useState<File|null>(null);const [status,setStatus]=useState<string|null>(null);return <Card title="Фото чека"><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/><button className="button primary full" disabled={!file} onClick={async()=>{if(!file)return;const b=await fileToDataUrl(file);setStatus('Сохраняем чек…');await post('/finance/receipts',{file_name:file.name,mime_type:file.type,image_data:b});setStatus('Чек сохранён. OCR/AI запускается через серверный адаптер при наличии настроек.');await p.onReload()}}>{status??'Загрузить чек'}</button>{p.receipts.map(r=><div className="receipt-row" key={r.id}><div><strong>{r.file_name??'Чек'}</strong><small>{r.ocr_status}</small></div><span>{new Date(r.created_at).toLocaleDateString('ru-RU')}</span></div>)}</Card>}
function CreditsPanel(p:{credits:Credit[]}){return <div className="stack">{p.credits.map(c=><Card key={c.id} title={c.name}><div className="credit-summary"><div><small>Остаток</small><strong>{rub(n(c.principal))}</strong></div><div><small>Ставка</small><strong>{c.annual_rate}%</strong></div><div><small>Платёж</small><strong>{rub(n(c.standard_payment))}</strong></div></div><div className="credit-list">{(c.payment_schedule??[]).slice(0,12).map((r:any,i:number)=><div className="credit-row" key={i}><span>Месяц {r.from_month===r.to_month?r.from_month:`${r.from_month}–${r.to_month}`}</span><strong>{rub(n(r.amount))}</strong></div>)}</div><button className="button secondary full">Показать ещё</button></Card>)}</div>}

function FormModal(p:{title:string;fields:{name:string;label:string;defaultValue:string}[];onClose:()=>void;onSave:(d:any)=>void}){const [data,setData]=useState<Record<string,string>>(()=>Object.fromEntries(p.fields.map(f=>[f.name,f.defaultValue])));return <div className="modal-backdrop"><div className="modal-sheet"><div className="modal-head"><h2>{p.title}</h2><button onClick={p.onClose}>×</button></div><div className="form-stack">{p.fields.map(f=><label key={f.name}>{f.label}<input value={data[f.name]??''} onChange={e=>setData({...data,[f.name]:e.target.value})}/></label>)}<div className="modal-actions"><button className="button secondary" onClick={p.onClose}>Отмена</button><button className="button primary" onClick={()=>p.onSave(data)}>Сохранить</button></div></div></div></div>}
function fileToDataUrl(f:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(f)})}
function pctVal(v:number){return Math.min(100,Math.max(0,v))}
function SectionTitle(p:{title:string;subtitle?:string;action?:ReactNode}){return <div className="section-title"><div><h2>{p.title}</h2>{p.subtitle&&<p>{p.subtitle}</p>}</div>{p.action}</div>}
function Card(p:{title:string;children:ReactNode;actions?:ReactNode}){return <section className="card"><div className="card-head"><h3>{p.title}</h3>{p.actions}</div>{p.children}</section>}
function Metric(p:{title:string;value:number}){return <div className="metric"><small>{p.title}</small><strong>{rub(p.value)}</strong></div>}
function pctAmountDummy(){return 0}
