<?php
namespace App\Http\Controllers\Api;
use App\Models\Event;
use App\Models\FamilyMember;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class EventController extends BaseApiController {
 public function index(Request $request): JsonResponse { $m=$this->membership($request); $q=Event::where('family_id',$m->family_id)->with(['creator','responsibleMember.user','participants.user'])->orderBy('start_at'); if($request->filled('from'))$q->where('start_at','>=',$request->input('from')); if($request->filled('to'))$q->where('start_at','<',$request->input('to')); if($request->filled('status'))$q->where('status',$request->input('status')); return response()->json(['data'=>$q->get()]); }
 public function show(Request $request, Event $event): JsonResponse { $m=$this->authorizeEvent($request,$event); $event->load(['creator','responsibleMember.user','participants.user']); return response()->json(['data'=>$event,'permissions'=>['can_update'=>$this->canManage($m,$event),'can_delete'=>$this->canManage($m,$event)]]); }
 public function store(Request $request): JsonResponse { $m=$this->membership($request); $d=$this->rules($request,true); $this->validateMembers($m,$d['responsible_member_id'],$d['participant_member_ids']??[]); $ids=collect($d['participant_member_ids']??[])->push($d['responsible_member_id'])->unique()->values(); $e=DB::transaction(function()use($d,$m,$ids){$e=Event::create(['family_id'=>$m->family_id,'created_by'=>$m->user_id,'title'=>$d['title'],'description'=>$d['description']??null,'start_at'=>$d['start_at'],'end_at'=>$d['end_at'],'timezone'=>$d['timezone']??'Europe/Moscow','location'=>$d['location']??null,'responsible_member_id'=>$d['responsible_member_id'],'source'=>'FAMILY_HUB','status'=>'SCHEDULED','recurrence_rule'=>$d['recurrence_rule']??null]);$e->participants()->sync($ids->all());return $e;}); return response()->json(['data'=>$e->load(['creator','responsibleMember.user','participants.user'])],201); }
 public function update(Request $request, Event $event): JsonResponse { $m=$this->authorizeEvent($request,$event); abort_unless($event->source==='FAMILY_HUB',422,'Apple Calendar events are read-only.'); abort_unless($this->canManage($m,$event),403); $d=$this->rules($request,false); $ids=null; if(isset($d['responsible_member_id'])||array_key_exists('participant_member_ids',$d)){ $rid=$d['responsible_member_id']??$event->responsible_member_id; $pids=$d['participant_member_ids']??$event->participants()->pluck('family_members.id')->all(); $this->validateMembers($m,$rid,$pids); $ids=collect($pids)->push($rid)->unique()->values(); } DB::transaction(function()use($event,$d,$ids){$event->update(collect($d)->except('participant_member_ids')->all());if($ids)$event->participants()->sync($ids->all());});return response()->json(['data'=>$event->fresh()->load(['creator','responsibleMember.user','participants.user'])]); }
 public function destroy(Request $request, Event $event): JsonResponse { $m=$this->authorizeEvent($request,$event); abort_unless($event->source==='FAMILY_HUB',422,'Apple Calendar events are read-only.'); abort_unless($this->canManage($m,$event),403); $event->delete(); return response()->json([],204); }
 private function rules(Request $r,bool $required):array{$req=$required?'required':'sometimes';return $r->validate(['title'=>[$req,'string','max:255'],'description'=>['nullable','string'],'start_at'=>[$req,'date'],'end_at'=>[$req,'date','after:start_at'],'timezone'=>['nullable','timezone'],'location'=>['nullable','string','max:255'],'responsible_member_id'=>[$req,'string','exists:family_members,id'],'participant_member_ids'=>['sometimes','array'],'participant_member_ids.*'=>['string','exists:family_members,id'],'status'=>['sometimes',Rule::in(['SCHEDULED','COMPLETED','CANCELLED'])],'recurrence_rule'=>['nullable','string','max:255']]);}
 private function validateMembers(FamilyMember $m,string $rid,array $pids):void{$ids=collect($pids)->push($rid)->unique();$count=FamilyMember::where('family_id',$m->family_id)->where('status','ACTIVE')->whereIn('id',$ids)->count();abort_unless($count===$ids->count(),422,'One or more participants do not belong to this family.');}
 private function authorizeEvent(Request $r,Event $e):FamilyMember{$m=$this->membership($r,$e->family_id);return $m;}
 private function canManage(FamilyMember $m,Event $e):bool{return $m->role==='ADMIN'||$e->created_by===$m->user_id;}
}
